import { getSupabaseClient } from '@/lib/supabase';
const client=()=>getSupabaseClient();
function unwrap<T>(data:T|null,error:{message:string}|null):T{if(error)throw new Error(error.message);if(data==null)throw new Error('Owner control-plane service returned no data.');return data;}
export async function getSession(){const{data,error}=await client().auth.getSession();if(error)throw error;return data.session;}
export async function getPlatformSnapshot(){const{data,error}=await client().rpc('admin_control_plane_snapshot');return unwrap(data as Record<string,unknown>|null,error);}
export async function getPlatformHistory(limit=50){const{data,error}=await client().rpc('admin_control_plane_history',{p_limit:limit});return unwrap(data as Record<string,unknown>|null,error);}
export async function listPendingBusinesses(){const{data,error}=await client().rpc('admin_list_pending_businesses');return unwrap(data??[],error);}
export async function getBusinessAccess(businessId:string){const{data,error}=await client().rpc('admin_get_business_access',{p_business_id:businessId});return unwrap(data,error);}
export async function setBusinessAccess(input:{businessId:string;tier:string;fleetEnabled:boolean;enterpriseEnabled:boolean;reason:string}){const{data,error}=await client().rpc('admin_set_business_access',{p_business_id:input.businessId,p_tier:input.tier,p_fleet_enabled:input.fleetEnabled,p_enterprise_enabled:input.enterpriseEnabled,p_reason:input.reason});return unwrap(data,error);}
export async function listBusinessMembers(businessId:string){const{data,error}=await client().rpc('admin_list_business_members',{p_business_id:businessId});return unwrap(data,error);}
export async function assignBusinessMember(businessId:string,userId:string,role:string){const{data,error}=await client().rpc('admin_assign_business_member',{p_business_id:businessId,p_user_id:userId,p_role:role});return unwrap(data,error);}
export async function removeBusinessMember(businessId:string,userId:string){const{data,error}=await client().rpc('admin_remove_business_member',{p_business_id:businessId,p_user_id:userId});return unwrap(data,error);}
export async function getCapabilityClassificationSummary(){const{data,error}=await client().rpc('capability_classification_summary');return unwrap(data??[],error);}
export async function getCapabilityRetirementAudit(limit=100){const{data,error}=await client().rpc('capability_retirement_audit',{p_limit:limit});return unwrap(data??[],error);}
export async function getSingleCapabilityDomainIssues(){const{data,error}=await client().rpc('check_single_capability_per_domain');return unwrap(data??[],error);}
export async function getRawSchemaCapabilityAudit(){const{data,error}=await client().rpc('admin_raw_schema_capability_audit');return unwrap(data,error);}
export async function getOperationalCapabilityCatalog(){const{data,error}=await client().rpc('admin_operational_capability_catalog');return unwrap(data,error);}
export async function getCrudCapabilityCatalog(){const{data,error}=await client().rpc('admin_crud_capability_catalog');return unwrap(data,error);}
export async function runCapabilityAudit(source='owner_app'){const{data,error}=await client().rpc('run_capability_audit',{p_source:source});return unwrap(data,error);}
export async function getOwnerAuditBundle(){const end=new Date(),start=new Date(end.getTime()-86400000);const[run,raw,domains,activity]=await Promise.all([client().rpc('run_capability_audit',{p_source:'owner_app'}),client().rpc('admin_raw_schema_capability_audit'),client().rpc('check_single_capability_per_domain'),client().rpc('admin_list_activity_events',{p_limit:100,p_from:start.toISOString(),p_to:end.toISOString()})]);for(const result of[run,raw,domains,activity])if(result.error)throw new Error(result.error.message);return{run:run.data,raw:raw.data,domains:domains.data,activity:activity.data};}
export async function getCapabilityCatalogBundle(){const[operational,crud,classifications,retirement,domainIssues]=await Promise.all([getOperationalCapabilityCatalog(),getCrudCapabilityCatalog(),getCapabilityClassificationSummary(),getCapabilityRetirementAudit(),getSingleCapabilityDomainIssues()]);return{operational,crud,classifications,retirement,domainIssues};}
const intelligenceRpc=(name:string,args:Record<string,unknown>)=>client().rpc(name,args).then(({data,error})=>unwrap(data,error));
export async function getOwnerIntelligence(scope:'business'|'fleet'|'enterprise',id:string){if(!id.trim())throw new Error(`A ${scope} ID is required.`);const key=scope==='business'?'p_business_id':scope==='fleet'?'p_fleet_id':'p_enterprise_id';const args={[key]:id.trim()};const names=scope==='business'?['business_growth_analytics','business_summary_analytics','business_engagement_analytics','business_campaign_analytics','business_roi_analytics','business_benchmark_analytics','get_business_growth_action_summary']:scope==='fleet'?['get_fleet_dashboard_summary','get_fleet_metric_capabilities','get_fleet_service_opportunities']:['get_enterprise_network_metrics','get_enterprise_campaign_roi','get_enterprise_partner_allocation_roi'];const settled=await Promise.allSettled(names.map(name=>intelligenceRpc(name,args)));return names.map((name,index)=>settled[index].status==='fulfilled'?{name,value:(settled[index] as PromiseFulfilledResult<unknown>).value}:{name,error:(settled[index] as PromiseRejectedResult).reason instanceof Error?(settled[index] as PromiseRejectedResult).reason.message:String((settled[index] as PromiseRejectedResult).reason)});}
export async function listReportingSchedules(){const{data,error}=await client().from('reporting_schedules').select('*').order('created_at',{ascending:false}).limit(100);return unwrap(data??[],error);}
export async function listReportingRuns(scheduleId?:string){let query=client().from('reporting_runs').select('*').order('created_at',{ascending:false}).limit(100);if(scheduleId)query=query.eq('schedule_id',scheduleId);const{data,error}=await query;return unwrap(data??[],error);}
export async function ownerCrudList(resource:string,limit=50){if(!/^[-_a-z0-9]+$/.test(resource))throw new Error('Choose a valid canonical resource.');const{data,error}=await client().rpc('admin_crud_gateway',{p_resource:resource,p_action:'list',p_id:null,p_payload:{limit:Math.min(Math.max(limit,1),100),order:'desc'}});return unwrap(data,error);}
export async function getOwnerOperations(){const end=new Date(),start=new Date(end.getTime()-86400000);const[overview,integrity,activity,reports,reviewReports,ingestion,push,nativePush,resources]=await Promise.all([client().rpc('admin_get_overview'),client().rpc('admin_data_integrity_summary'),client().rpc('admin_list_activity_events',{p_limit:100}),client().rpc('admin_list_reports'),client().rpc('admin_list_review_reports',{p_status:null}),client().rpc('admin_national_ingestion_status'),client().rpc('admin_notification_push_delivery_summary',{p_from:start.toISOString(),p_to:end.toISOString()}),client().rpc('admin_notification_native_push_delivery_health',{p_from:start.toISOString(),p_to:end.toISOString()}),client().rpc('admin_backend_resource_catalog')]);for(const r of[overview,integrity,activity,reports,reviewReports,ingestion,push,nativePush,resources])if(r.error)throw new Error(r.error.message);return{overview:overview.data,integrity:integrity.data,activity:activity.data,reports:reports.data,reviewReports:reviewReports.data,ingestion:ingestion.data,push:push.data,nativePush:nativePush.data,resources:resources.data};}
export async function resolveReviewReport(reportId:string,resolution:string,reason:string,reviewStatus:string){const{data,error}=await client().rpc('admin_resolve_review_report',{p_report_id:reportId,p_resolution:resolution,p_reason:reason,p_review_status:reviewStatus});return unwrap(data,error);}
export async function getOwnerControlPlaneBundle(){const[snapshot,history,pending,classifications,retirement,domainIssues,raw,operational,crud]=await Promise.all([getPlatformSnapshot(),getPlatformHistory(),listPendingBusinesses(),getCapabilityClassificationSummary(),getCapabilityRetirementAudit(),getSingleCapabilityDomainIssues(),getRawSchemaCapabilityAudit(),getOperationalCapabilityCatalog(),getCrudCapabilityCatalog()]);return{snapshot,history,pending,classifications,retirement,domainIssues,raw,operational,crud};}
