import { useCallback,useEffect,useState } from 'react';
import { ActivityIndicator,Pressable,RefreshControl,ScrollView,Text,TextInput,View } from 'react-native';
import { ActionSheetCard,EntityRow,OSHero,PrimaryAction,SectionHeader,StatusPill,osColors } from '@/components/KleenestOS';
import { getOwnerModerationQueues,resolveOwnerReviewReport } from '@/services/ownerModeration';

type Queues=Awaited<ReturnType<typeof getOwnerModerationQueues>>;
export default function ModerationConsole(){
 const[data,setData]=useState<Queues|null>(null),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState<string|null>(null),[selected,setSelected]=useState<any|null>(null),[resolution,setResolution]=useState<'dismiss'|'hide'|'restore'>('hide'),[reason,setReason]=useState('KleenestOS moderation decision'),[busy,setBusy]=useState(false),[message,setMessage]=useState<string|null>(null);
 const load=useCallback(async()=>{setError(null);setData(await getOwnerModerationQueues())},[]);
 useEffect(()=>{load().catch(c=>setError(c instanceof Error?c.message:String(c))).finally(()=>setLoading(false))},[load]);
 async function refresh(){setRefreshing(true);try{await load()}catch(c){setError(c instanceof Error?c.message:String(c))}finally{setRefreshing(false)}}
 async function resolve(){if(!selected)return;setBusy(true);setError(null);setMessage(null);try{await resolveOwnerReviewReport({reportId:String(selected.id),resolution,reason});await load();setSelected(null);setMessage('Moderation decision applied through canonical authority.')}catch(c){setError(c instanceof Error?c.message:String(c))}finally{setBusy(false)}}
 if(loading)return <View style={{flex:1,justifyContent:'center'}}><ActivityIndicator size="large"/></View>;
 return <ScrollView contentInsetAdjustmentBehavior="automatic" refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh}/>} contentContainerStyle={{padding:16,gap:16,paddingBottom:60}}>
  <OSHero eyebrow="KLEENESTOS · TRUST & MODERATION" title="Trust & Moderation" body="Resolve reports and pending trust work from real queues. Decisions are server-authoritative and reasoned."/>
  {error?<Text style={{color:osColors.danger,fontWeight:'800'}}>{error}</Text>:null}{message?<Text style={{color:osColors.good,fontWeight:'800'}}>{message}</Text>:null}
  <View style={{gap:9}}><SectionHeader title="Review reports" body={`${data?.reviewReports.length??0} pending`}/>{data?.reviewReports.length?data.reviewReports.map((report:any)=><EntityRow key={String(report.id)} title={String(report.reason??'Reported review')} subtitle={String(report.details??'No additional details')} meta={report.created_at?new Date(String(report.created_at)).toLocaleString():''} onPress={()=>setSelected(report)}><StatusPill label="PENDING" tone="warning"/></EntityRow>):<EntityRow title="Review queue clear" subtitle="No pending review reports."><StatusPill label="HEALTHY" tone="good"/></EntityRow>}</View>
  <View style={{gap:9}}><SectionHeader title="Pending businesses" body={`${data?.pendingBusinesses.length??0} waiting for administrative review`}/>{data?.pendingBusinesses.length?data.pendingBusinesses.map((business:any,index)=><EntityRow key={String(business.id??index)} title={String(business.name??business.business_name??'Pending business')} subtitle={String(business.verification_status??business.status??'pending')} meta={String(business.id??'')}/>):<EntityRow title="Business queue clear" subtitle="No pending businesses returned by the canonical queue."><StatusPill label="HEALTHY" tone="good"/></EntityRow>}</View>
  {selected?<ActionSheetCard title="Resolve review report" body="Choose a real moderation outcome. A reason is required by server authority."><View style={{flexDirection:'row',gap:7,flexWrap:'wrap'}}>{(['hide','dismiss','restore'] as const).map(value=><Pressable key={value} onPress={()=>setResolution(value)}><StatusPill label={value.toUpperCase()} tone={resolution===value?(value==='hide'?'danger':'good'):'neutral'}/></Pressable>)}</View><TextInput value={reason} onChangeText={setReason} placeholder="Reason" style={input}/><View style={{flexDirection:'row',gap:8,flexWrap:'wrap'}}><PrimaryAction label={busy?'Applying…':'Apply moderation decision'} onPress={resolve} disabled={busy||!reason.trim()}/><PrimaryAction label="Cancel" onPress={()=>setSelected(null)} disabled={busy}/></View></ActionSheetCard>:null}
 </ScrollView>
}
const input={backgroundColor:'white',borderRadius:12,paddingHorizontal:12,paddingVertical:11,borderWidth:1,borderColor:osColors.border,color:osColors.ink} as const;
