import { useCallback,useEffect,useState } from 'react';
import { ActivityIndicator,Pressable,RefreshControl,ScrollView,Text,TextInput,View } from 'react-native';
import { ActionSheetCard,EntityRow,OSHero,PrimaryAction,SectionHeader,StatusPill,osColors } from '@/components/KleenestOS';
import { getOwnerModerationQueues,resolveOwnerAiResponseReport,resolveOwnerReviewReport,resolveOwnerUserSafetyReport } from '@/services/ownerModeration';

type Queues=Awaited<ReturnType<typeof getOwnerModerationQueues>>;
type Selection={kind:'review'|'user'|'ai';row:any};
export default function ModerationConsole(){
 const[data,setData]=useState<Queues|null>(null),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState<string|null>(null),[selected,setSelected]=useState<Selection|null>(null),[reviewResolution,setReviewResolution]=useState<'dismiss'|'hide'|'restore'>('hide'),[safetyStatus,setSafetyStatus]=useState<'reviewing'|'resolved'|'dismissed'>('resolved'),[reason,setReason]=useState('KleenestOS moderation decision'),[busy,setBusy]=useState(false),[message,setMessage]=useState<string|null>(null);
 const load=useCallback(async()=>{setError(null);setData(await getOwnerModerationQueues())},[]);
 useEffect(()=>{load().catch(c=>setError(c instanceof Error?c.message:String(c))).finally(()=>setLoading(false))},[load]);
 async function refresh(){setRefreshing(true);try{await load()}catch(c){setError(c instanceof Error?c.message:String(c))}finally{setRefreshing(false)}}
 async function resolve(){if(!selected)return;setBusy(true);setError(null);setMessage(null);try{const id=String(selected.row.id);if(selected.kind==='review')await resolveOwnerReviewReport({reportId:id,resolution:reviewResolution,reason});if(selected.kind==='user')await resolveOwnerUserSafetyReport({reportId:id,status:safetyStatus});if(selected.kind==='ai')await resolveOwnerAiResponseReport({reportId:id,status:safetyStatus,resolution:reason});await load();setSelected(null);setMessage('Moderation decision applied through canonical server authority.')}catch(c){setError(c instanceof Error?c.message:String(c))}finally{setBusy(false)}}
 if(loading)return <View style={{flex:1,justifyContent:'center'}}><ActivityIndicator size="large"/></View>;
 const pending=(data?.reviewReports.length??0)+(data?.userReports.length??0)+(data?.aiReports.length??0);
 return <ScrollView contentInsetAdjustmentBehavior="automatic" refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh}/>} contentContainerStyle={{padding:16,gap:16,paddingBottom:60}}>
  <OSHero eyebrow="KLEENESTOS · TRUST & MODERATION" title="Trust & Moderation" body={`${pending} open safety item${pending===1?'':'s'}. Resolve review, contributor and AI reports from real server-authoritative queues.`}/>
  {error?<Text style={{color:osColors.danger,fontWeight:'800'}}>{error}</Text>:null}{message?<Text style={{color:osColors.good,fontWeight:'800'}}>{message}</Text>:null}

  <View style={{gap:9}}><SectionHeader title="Review reports" body={`${data?.reviewReports.length??0} pending`}/>{data?.reviewReports.length?data.reviewReports.map((report:any)=><EntityRow key={String(report.id)} title={String(report.reason??'Reported review')} subtitle={String(report.details??'No additional details')} meta={report.created_at?new Date(String(report.created_at)).toLocaleString():''} onPress={()=>setSelected({kind:'review',row:report})}><StatusPill label="PENDING" tone="warning"/></EntityRow>):<EntityRow title="Review queue clear" subtitle="No pending review reports."><StatusPill label="HEALTHY" tone="good"/></EntityRow>}</View>

  <View style={{gap:9}}><SectionHeader title="Contributor safety reports" body={`${data?.userReports.length??0} open`}/>{data?.userReports.length?data.userReports.map((report:any)=><EntityRow key={String(report.id)} title={`${String(report.reason??'Safety report')} · ${String(report.reported_name??'Contributor')}`} subtitle={String(report.details??`Context: ${report.context??'profile'}`)} meta={report.created_at?new Date(String(report.created_at)).toLocaleString():''} onPress={()=>setSelected({kind:'user',row:report})}><StatusPill label="OPEN" tone="danger"/></EntityRow>):<EntityRow title="Contributor safety queue clear" subtitle="No open contributor reports."><StatusPill label="HEALTHY" tone="good"/></EntityRow>}</View>

  <View style={{gap:9}}><SectionHeader title="AI response reports" body={`${data?.aiReports.length??0} open`}/>{data?.aiReports.length?data.aiReports.map((report:any)=><EntityRow key={String(report.id)} title={`${String(report.reason??'AI report')} · ${String(report.task??'AI assist')}`} subtitle={String(report.details??report.answer_excerpt??'No additional details').slice(0,220)} meta={[report.provider,report.model,report.created_at?new Date(String(report.created_at)).toLocaleString():null].filter(Boolean).join(' · ')} onPress={()=>{setReason('KleenestOS AI safety review');setSelected({kind:'ai',row:report})}}><StatusPill label="OPEN" tone="danger"/></EntityRow>):<EntityRow title="AI safety queue clear" subtitle="No open AI response reports."><StatusPill label="HEALTHY" tone="good"/></EntityRow>}</View>

  <View style={{gap:9}}><SectionHeader title="Pending businesses" body={`${data?.pendingBusinesses.length??0} waiting for administrative review`}/>{data?.pendingBusinesses.length?data.pendingBusinesses.map((business:any,index)=><EntityRow key={String(business.id??index)} title={String(business.name??business.business_name??'Pending business')} subtitle={String(business.verification_status??business.status??'pending')} meta={String(business.id??'')}/>):<EntityRow title="Business queue clear" subtitle="No pending businesses returned by the canonical queue."><StatusPill label="HEALTHY" tone="good"/></EntityRow>}</View>

  {selected?<ActionSheetCard title={selected.kind==='review'?'Resolve review report':selected.kind==='user'?'Resolve contributor safety report':'Resolve AI response report'} body={selected.kind==='ai'?`Trace ${String(selected.row.trace_id??'unknown')} · ${String(selected.row.answer_excerpt??'').slice(0,400)}`:'Apply a real moderation outcome through server authority.'}>{selected.kind==='review'?<View style={{flexDirection:'row',gap:7,flexWrap:'wrap'}}>{(['hide','dismiss','restore'] as const).map(value=><Pressable key={value} onPress={()=>setReviewResolution(value)}><StatusPill label={value.toUpperCase()} tone={reviewResolution===value?(value==='hide'?'danger':'good'):'neutral'}/></Pressable>)}</View>:<View style={{flexDirection:'row',gap:7,flexWrap:'wrap'}}>{(['reviewing','resolved','dismissed'] as const).map(value=><Pressable key={value} onPress={()=>setSafetyStatus(value)}><StatusPill label={value.toUpperCase()} tone={safetyStatus===value?(value==='resolved'?'good':value==='dismissed'?'neutral':'warning'):'neutral'}/></Pressable>)}</View>}<TextInput value={reason} onChangeText={setReason} placeholder="Reason / resolution note" multiline style={input}/><View style={{flexDirection:'row',gap:8,flexWrap:'wrap'}}><PrimaryAction label={busy?'Applying…':'Apply moderation decision'} onPress={resolve} disabled={busy||!reason.trim()}/><PrimaryAction label="Cancel" onPress={()=>setSelected(null)} disabled={busy}/></View></ActionSheetCard>:null}
 </ScrollView>
}
const input={backgroundColor:'white',borderRadius:12,paddingHorizontal:12,paddingVertical:11,borderWidth:1,borderColor:osColors.border,color:osColors.ink,minHeight:72,textAlignVertical:'top'} as const;
