import { useCallback,useEffect,useState } from 'react';
import { ActivityIndicator,RefreshControl,ScrollView,Text,View } from 'react-native';
import { card,colors,ErrorBanner,Hero } from '@/components/OwnerUI';
import { getOwnerProgressionPlatformSnapshot,type OwnerProgressionPlatformSnapshot } from '@/services/progression';

export default function OwnerProgressionPage(){
 const[data,setData]=useState<OwnerProgressionPlatformSnapshot|null>(null),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{setError(null);setData(await getOwnerProgressionPlatformSnapshot())},[]);
 useEffect(()=>{load().catch(c=>setError(c instanceof Error?c.message:String(c))).finally(()=>setLoading(false))},[load]);
 async function refresh(){setRefreshing(true);try{await load()}catch(c){setError(c instanceof Error?c.message:String(c))}finally{setRefreshing(false)}}
 if(loading)return <View style={{flex:1,justifyContent:'center'}}><ActivityIndicator size="large"/></View>;
 const onsitePct=(data?.discoveries??0)>0?Math.round(((data?.on_site_discoveries??0)/(data?.discoveries??1))*100):0;
 return <ScrollView contentInsetAdjustmentBehavior="automatic" refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh}/>} contentContainerStyle={{padding:16,gap:16,paddingBottom:56}}>
  <Hero eyebrow="PROGRESSION CONTROL PLANE" title="Discovery + XP platform" body="Private oversight of the canonical discovery, evidence and progression stream shared across Consumer, Business and Fleet."/>
  <ErrorBanner message={error}/>
  <View style={{flexDirection:'row',flexWrap:'wrap',gap:10}}><Metric label="Users with XP" value={data?.users_with_xp??0}/><Metric label="XP awarded" value={data?.xp_awarded??0}/><Metric label="Discoveries" value={data?.discoveries??0}/><Metric label="On-site evidence" value={data?.on_site_discoveries??0}/><Metric label="On-site share" value={onsitePct} suffix="%"/><Metric label="Discovery photos" value={data?.discovery_photos??0}/><Metric label="Active objectives" value={data?.active_objectives??0}/></View>
  <View style={{...card,backgroundColor:'#132b21',gap:7}}><Text style={{color:'#bfe0cb',fontWeight:'900',fontSize:11,letterSpacing:1}}>XP ECONOMY HEALTH</Text><Text style={{color:'white',fontSize:20,fontWeight:'900'}}>Remote discovery and live evidence remain intentionally distinct.</Text><Text style={{color:'#dbe8e0',lineHeight:20}}>The platform records source method and evidence tier independently of XP. On-site evidence can earn more without silently converting sponsorship, activity or repetition into verification authority.</Text></View>
  <Section title="Active objective mix">{Object.keys(data?.objective_kinds??{}).length?Object.entries(data?.objective_kinds??{}).map(([kind,count])=><View key={kind} style={card}><Text style={{fontWeight:'900',fontSize:16,textTransform:'capitalize'}}>{kind}</Text><Text style={{color:colors.muted}}>{Number(count).toLocaleString()} active</Text></View>):<Text style={{color:colors.muted}}>No active v2 objectives.</Text>}</Section>
  <Section title="Awards by action">{data?.awards_by_action?.length?data.awards_by_action.map(item=><View key={item.action} style={card}><View style={{flexDirection:'row',justifyContent:'space-between',gap:10}}><Text style={{fontWeight:'900',fontSize:15,flex:1}}>{String(item.action).replaceAll('_',' ')}</Text><Text style={{fontWeight:'900',color:'#17613c'}}>{Number(item.xp||0).toLocaleString()} XP</Text></View><Text style={{color:colors.muted}}>{Number(item.events||0).toLocaleString()} canonical awards</Text></View>):<Text style={{color:colors.muted}}>No v2 XP awards yet.</Text>}</Section>
  <Section title="Recent discoveries">{data?.recent_discoveries?.length?data.recent_discoveries.map((item,index)=><View key={`${item.created_at}-${index}`} style={card}><Text style={{fontWeight:'900',fontSize:15,textTransform:'capitalize'}}>{String(item.method||'remote').replaceAll('_',' ')} · tier {item.tier}</Text><Text style={{color:colors.muted,textTransform:'capitalize'}}>{String(item.state||'candidate').replaceAll('_',' ')} · location {String(item.location_id||'').slice(0,8)}…</Text><Text style={{color:colors.muted,fontSize:11}}>{item.created_at?new Date(item.created_at).toLocaleString():''}</Text></View>):<Text style={{color:colors.muted}}>No discovery contributions recorded yet.</Text>}</Section>
 </ScrollView>
}
function Metric({label,value,suffix=''}:{label:string;value:number;suffix?:string}){return <View style={{...card,minWidth:125,flexGrow:1}}><Text style={{color:colors.muted,fontSize:12,fontWeight:'700'}}>{label}</Text><Text style={{fontSize:24,fontWeight:'800',fontVariant:['tabular-nums']}}>{Number(value||0).toLocaleString()}{suffix}</Text></View>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <View style={{gap:9}}><Text style={{fontSize:22,fontWeight:'900'}}>{title}</Text>{children}</View>}
