import { useCallback,useEffect,useState } from 'react';
import { ActivityIndicator,Pressable,RefreshControl,ScrollView,Text,TextInput,View } from 'react-native';
import { ActionSheetCard,EntityRow,HealthCard,OSHero,PrimaryAction,SectionHeader,StatusPill,osColors } from '@/components/KleenestOS';
import { getOwnerEconomySnapshot,updateOwnerXpAction } from '@/services/ownerEconomy';

type Economy=Awaited<ReturnType<typeof getOwnerEconomySnapshot>>;
const tierLabels:Record<string,string>={'1':'Remote assertion','2':'Corroborated remote','3':'GPS-supported','4':'On-site live','5':'Independent confirmation','6':'Verified'};

export default function OwnerEconomyPage(){
 const[data,setData]=useState<Economy|null>(null),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState<string|null>(null),[selectedAction,setSelectedAction]=useState<any|null>(null),[baseXp,setBaseXp]=useState('0'),[cooldown,setCooldown]=useState('0'),[maxPerDay,setMaxPerDay]=useState(''),[enabled,setEnabled]=useState(true),[reason,setReason]=useState('KleenestOS XP economy tuning'),[saving,setSaving]=useState(false),[message,setMessage]=useState<string|null>(null);
 const load=useCallback(async()=>{setError(null);setData(await getOwnerEconomySnapshot())},[]);
 useEffect(()=>{load().catch(c=>setError(c instanceof Error?c.message:String(c))).finally(()=>setLoading(false))},[load]);
 async function refresh(){setRefreshing(true);try{await load()}catch(c){setError(c instanceof Error?c.message:String(c))}finally{setRefreshing(false)}}
 function chooseAction(item:any){setSelectedAction(item);setBaseXp(String(item.base_xp??0));setCooldown(String(item.cooldown_seconds??0));setMaxPerDay(item.max_per_day==null?'':String(item.max_per_day));setEnabled(Boolean(item.enabled));setMessage(null)}
 async function saveAction(){if(!selectedAction)return;setSaving(true);setError(null);setMessage(null);try{await updateOwnerXpAction({action:String(selectedAction.action),baseXp:Number(baseXp),cooldownSeconds:Number(cooldown),maxPerDay:maxPerDay.trim()?Number(maxPerDay):null,enabled,reason});await load();setSelectedAction(null);setMessage('XP action policy updated and audited.')}catch(c){setError(c instanceof Error?c.message:String(c))}finally{setSaving(false)}}
 if(loading)return <View style={{flex:1,justifyContent:'center'}}><ActivityIndicator size="large"/></View>;
 const velocityDelta=(data?.xpPrev24h??0)>0?Math.round((((data?.xpLast24h??0)-(data?.xpPrev24h??0))/(data?.xpPrev24h??1))*100):null;
 return <ScrollView contentInsetAdjustmentBehavior="automatic" refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh}/>} contentContainerStyle={{padding:16,gap:16,paddingBottom:64}}>
  <OSHero eyebrow="KLEENESTOS · ECONOMY" title="Economy" body="Operate the live XP, discovery and objective economy. Metrics come from canonical progression events and controls write through owner-only audited RPC authority."/>
  {error?<Text style={{color:osColors.danger,fontWeight:'800'}}>{error}</Text>:null}{message?<Text style={{color:osColors.good,fontWeight:'800'}}>{message}</Text>:null}
  <View style={{flexDirection:'row',flexWrap:'wrap',gap:10}}><HealthCard label="XP issuance" value={Number(data?.xpAwarded??0).toLocaleString()} detail={`${Number(data?.xpLast24h??0).toLocaleString()} in 24h${velocityDelta==null?'':` · ${velocityDelta>=0?'+':''}${velocityDelta}%`}`}/><HealthCard label="Participants" value={Number(data?.usersWithXp??0).toLocaleString()} detail="Users with awarded v2 XP"/><HealthCard label="Discoveries" value={Number(data?.discoveries??0).toLocaleString()} detail={`${Number(data?.onSiteDiscoveries??0).toLocaleString()} on-site live`}/><HealthCard label="Objectives" value={Number(data?.activeObjectives??0).toLocaleString()} detail="Active across all objective kinds"/></View>
  <View style={{gap:9}}><SectionHeader title="Evidence tiers" body="Discovery confidence and XP strength are distinct, visible operating signals."/>{data?.evidenceTiers.map((item:any)=><EntityRow key={String(item.tier)} title={tierLabels[String(item.tier)]??`Tier ${item.tier}`} subtitle={`${Number(item.count??0).toLocaleString()} discoveries`}><StatusPill label={`TIER ${item.tier}`} tone={Number(item.tier)>=4?'good':'neutral'}/></EntityRow>)}</View>
  <View style={{gap:9}}><SectionHeader title="Level distribution" body="Actual user distribution derived from awarded XP and canonical global thresholds."/>{data?.levelDistribution.map((item:any)=><EntityRow key={String(item.level)} title={`Level ${item.level}`} subtitle={`${Number(item.users??0).toLocaleString()} users`}/>)}</View>
  <View style={{gap:9}}><SectionHeader title="Objective mix" body="Quests, missions, challenges, journeys, campaigns and contests share the same canonical event stream."/>{Object.entries(data?.objectiveKinds??{}).map(([kind,count])=><EntityRow key={kind} title={kind.replaceAll('_',' ')} subtitle={`${Number(count).toLocaleString()} active`}/>)}</View>
  <View style={{gap:9}}><SectionHeader title="XP by action" body="Where the economy is issuing value right now."/>{data?.awardsByAction.slice(0,20).map((item:any)=><EntityRow key={String(item.action)} title={String(item.action).replaceAll('_',' ')} subtitle={`${Number(item.xp??0).toLocaleString()} XP`} meta={`${Number(item.events??0).toLocaleString()} awards`}/>)}</View>
  <View style={{gap:9}}><SectionHeader title="Suspicious velocity" body="Candidates are surfaced for review when 24-hour reward volume is unusually high."/>{data?.anomalyCandidates.length?data.anomalyCandidates.map((item:any)=><EntityRow key={String(item.user_id)} title={`User ${String(item.user_id).slice(0,8)}…`} subtitle={`${Number(item.xp_24h??0).toLocaleString()} XP in 24h`} meta={`${Number(item.events_24h??0).toLocaleString()} events`}><StatusPill label="REVIEW" tone="warning"/></EntityRow>):<EntityRow title="No current anomaly candidates" subtitle="No user crossed the configured high-velocity review threshold in the last 24 hours."><StatusPill label="HEALTHY" tone="good"/></EntityRow>}</View>
  <View style={{gap:9}}><SectionHeader title="XP policy controls" body="Select an action to change base XP, cooldown, daily cap or enablement. Every change is platform-owner-only and audited."/>{data?.xpActionCatalog.map((item:any)=><EntityRow key={String(item.action)} title={String(item.action).replaceAll('_',' ')} subtitle={`${Number(item.base_xp??0)} base XP · ${Number(item.cooldown_seconds??0)}s cooldown`} meta={`${item.max_per_day==null?'No daily cap':`${item.max_per_day}/day`} · ${item.enabled?'Enabled':'Disabled'}`} onPress={()=>chooseAction(item)}/>)}</View>
  {selectedAction?<ActionSheetCard title={`Tune ${String(selectedAction.action).replaceAll('_',' ')}`} body="This changes the live reward policy. Verification confidence remains separate from XP."><Text style={label}>Base XP</Text><TextInput keyboardType="number-pad" value={baseXp} onChangeText={setBaseXp} style={input}/><Text style={label}>Cooldown seconds</Text><TextInput keyboardType="number-pad" value={cooldown} onChangeText={setCooldown} style={input}/><Text style={label}>Max per day (blank = unlimited)</Text><TextInput keyboardType="number-pad" value={maxPerDay} onChangeText={setMaxPerDay} style={input}/><Pressable onPress={()=>setEnabled(v=>!v)}><StatusPill label={enabled?'ENABLED':'DISABLED'} tone={enabled?'good':'danger'}/></Pressable><Text style={label}>Audit reason</Text><TextInput value={reason} onChangeText={setReason} style={input}/><View style={{flexDirection:'row',gap:8,flexWrap:'wrap'}}><PrimaryAction label={saving?'Saving…':'Apply XP policy'} onPress={saveAction} disabled={saving||!reason.trim()}/><PrimaryAction label="Cancel" onPress={()=>setSelectedAction(null)} disabled={saving}/></View></ActionSheetCard>:null}
  <View style={{gap:9}}><SectionHeader title="Recent high-value events"/>{data?.recentHighValueEvents.slice(0,15).map((item:any)=><EntityRow key={String(item.id)} title={String(item.action).replaceAll('_',' ')} subtitle={`${Number(item.xp_awarded??0).toLocaleString()} XP · evidence tier ${Number(item.evidence_tier??0)}`} meta={item.created_at?new Date(String(item.created_at)).toLocaleString():''}/>)}</View>
 </ScrollView>
}

const label={fontWeight:'900',color:osColors.ink,fontSize:12} as const;
const input={backgroundColor:'white',borderRadius:12,paddingHorizontal:12,paddingVertical:11,borderWidth:1,borderColor:osColors.border,color:osColors.ink} as const;
