import { useCallback,useEffect,useMemo,useState } from 'react';
import { ActivityIndicator,Pressable,RefreshControl,ScrollView,Text,TextInput,View } from 'react-native';
import { ActionSheetCard,EntityRow,HealthCard,OSHero,PrimaryAction,SectionHeader,StatusPill,osColors } from '@/components/KleenestOS';
import { deleteOwnerProgressionObjective,getOwnerEconomySnapshot,getOwnerProgressionSupplyStatus,listOwnerProgressionObjectives,maintainOwnerProgressionSupply,saveOwnerProgressionObjective,setOwnerProgressionObjectiveStatus,updateOwnerXpAction,type OwnerProgressionObjective,type OwnerProgressionSupplyStatus } from '@/services/ownerEconomy';

type Economy=Awaited<ReturnType<typeof getOwnerEconomySnapshot>>;
type Kind=OwnerProgressionObjective['kind'];
const kinds:Kind[]=['quest','mission','challenge','journey','campaign','contest'];
const statuses=['draft','scheduled','active','paused','ended','archived'] as const;
const commonActions=['discover_any','discover_gps','discover_onsite_live','verify_location','reverify_stale','add_amenity','add_accessibility','add_photo','substantive_review','helpful_contribution','fleet_stop_complete'];
const tierLabels:Record<string,string>={'1':'Remote assertion','2':'Corroborated remote','3':'GPS-supported','4':'On-site live','5':'Independent confirmation','6':'Verified'};

function parseOptionalIso(value:string,label:string){const text=value.trim();if(!text)return null;const date=new Date(text);if(Number.isNaN(date.getTime()))throw new Error(`${label} must be a valid date/time.`);return date.toISOString();}
function ruleValue(record:Record<string,unknown>|null|undefined,key:string,fallback:string){const value=record?.[key];return value==null?fallback:String(value)}
function titleCase(value:string){return value.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}

export default function OwnerEconomyPage(){
 const[data,setData]=useState<Economy|null>(null),[objectives,setObjectives]=useState<OwnerProgressionObjective[]>([]),[supply,setSupply]=useState<OwnerProgressionSupplyStatus|null>(null),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState<string|null>(null),[selectedAction,setSelectedAction]=useState<any|null>(null),[baseXp,setBaseXp]=useState('0'),[cooldown,setCooldown]=useState('0'),[maxPerDay,setMaxPerDay]=useState(''),[enabled,setEnabled]=useState(true),[reason,setReason]=useState('KleenestOS progression control'),[saving,setSaving]=useState(false),[message,setMessage]=useState<string|null>(null);
 const[editingObjective,setEditingObjective]=useState<OwnerProgressionObjective|null|undefined>(undefined),[kind,setKind]=useState<Kind>('quest'),[objectiveCode,setObjectiveCode]=useState(''),[objectiveTitle,setObjectiveTitle]=useState(''),[objectiveDescription,setObjectiveDescription]=useState(''),[objectiveStatus,setObjectiveStatus]=useState('draft'),[objectiveAction,setObjectiveAction]=useState('discover_any'),[objectiveTarget,setObjectiveTarget]=useState('1'),[objectiveXp,setObjectiveXp]=useState('100'),[objectiveAudience,setObjectiveAudience]=useState('consumer'),[startsAt,setStartsAt]=useState(''),[endsAt,setEndsAt]=useState('');
 const load=useCallback(async()=>{setError(null);const[nextData,nextObjectives,nextSupply]=await Promise.all([getOwnerEconomySnapshot(),listOwnerProgressionObjectives(),getOwnerProgressionSupplyStatus()]);setData(nextData);setObjectives(nextObjectives);setSupply(nextSupply)},[]);
 useEffect(()=>{load().catch(c=>setError(c instanceof Error?c.message:String(c))).finally(()=>setLoading(false))},[load]);
 async function refresh(){setRefreshing(true);try{await load()}catch(c){setError(c instanceof Error?c.message:String(c))}finally{setRefreshing(false)}}
 function chooseAction(item:any){setSelectedAction(item);setBaseXp(String(item.base_xp??0));setCooldown(String(item.cooldown_seconds??0));setMaxPerDay(item.max_per_day==null?'':String(item.max_per_day));setEnabled(Boolean(item.enabled));setReason('KleenestOS XP economy tuning');setMessage(null)}
 async function saveAction(){if(!selectedAction)return;setSaving(true);setError(null);setMessage(null);try{await updateOwnerXpAction({action:String(selectedAction.action),baseXp:Number(baseXp),cooldownSeconds:Number(cooldown),maxPerDay:maxPerDay.trim()?Number(maxPerDay):null,enabled,reason});await load();setSelectedAction(null);setMessage('XP action policy updated and audited.')}catch(c){setError(c instanceof Error?c.message:String(c))}finally{setSaving(false)}}
 function beginCreate(){setEditingObjective(null);setKind('quest');setObjectiveCode(`owner-${Date.now()}`);setObjectiveTitle('');setObjectiveDescription('');setObjectiveStatus('draft');setObjectiveAction('discover_any');setObjectiveTarget('1');setObjectiveXp('100');setObjectiveAudience('consumer');setStartsAt('');setEndsAt('');setReason('Create platform progression objective');setMessage(null)}
 function beginEdit(item:OwnerProgressionObjective){setEditingObjective(item);setKind(item.kind);setObjectiveCode(item.code);setObjectiveTitle(item.title);setObjectiveDescription(item.description??'');setObjectiveStatus(item.status);setObjectiveAction(ruleValue(item.rules,'action','discover_any'));setObjectiveTarget(ruleValue(item.rules,'target','1'));setObjectiveXp(ruleValue(item.rewards,'xp','0'));setObjectiveAudience(ruleValue(item.scope,'audience','consumer'));setStartsAt(item.starts_at??'');setEndsAt(item.ends_at??'');setReason(`Update ${item.title}`);setMessage(null)}
 async function saveObjective(){const target=Number(objectiveTarget),xp=Number(objectiveXp);if(!Number.isFinite(target)||target<1)throw new Error('Objective target must be at least 1.');if(!Number.isFinite(xp)||xp<0)throw new Error('Objective XP must be zero or greater.');setSaving(true);setError(null);setMessage(null);try{await saveOwnerProgressionObjective({id:editingObjective?.id??null,kind,code:objectiveCode,title:objectiveTitle,description:objectiveDescription,status:objectiveStatus,startsAt:parseOptionalIso(startsAt,'Start'),endsAt:parseOptionalIso(endsAt,'End'),action:objectiveAction,target:Math.round(target),xpReward:Math.round(xp),audience:objectiveAudience,reason});await load();setEditingObjective(undefined);setMessage(editingObjective?'Objective updated and audited.':'Objective created and audited.')}catch(c){setError(c instanceof Error?c.message:String(c))}finally{setSaving(false)}}
 async function changeObjectiveStatus(item:OwnerProgressionObjective,status:string){setSaving(true);setError(null);setMessage(null);try{await setOwnerProgressionObjectiveStatus(item.id,status,`${titleCase(status)} ${item.title} from KleenestOS`);await load();setMessage(`${item.title} is now ${status}.`)}catch(c){setError(c instanceof Error?c.message:String(c))}finally{setSaving(false)}}
 async function deleteObjective(item:OwnerProgressionObjective){setSaving(true);setError(null);setMessage(null);try{await deleteOwnerProgressionObjective(item.id,`Delete unused ${item.title} from KleenestOS`);await load();setEditingObjective(undefined);setMessage('Objective deleted. Objectives with participant history are protected and must be archived instead.')}catch(c){setError(c instanceof Error?c.message:String(c))}finally{setSaving(false)}}
 async function runSupply(){setSaving(true);setError(null);setMessage(null);try{const result=await maintainOwnerProgressionSupply() as Record<string,unknown>;await load();setMessage(`Progression supply refreshed · ${Number(result?.created_count??0)} created · ${Number(result?.expired_count??0)} expired.`)}catch(c){setError(c instanceof Error?c.message:String(c))}finally{setSaving(false)}}
 const objectiveSummary=useMemo(()=>{const counts:Record<string,number>={};for(const item of objectives)counts[item.kind]=(counts[item.kind]??0)+1;return counts},[objectives]);
 if(loading)return <View style={{flex:1,justifyContent:'center'}}><ActivityIndicator size="large"/></View>;
 const velocityDelta=(data?.xpPrev24h??0)>0?Math.round((((data?.xpLast24h??0)-(data?.xpPrev24h??0))/(data?.xpPrev24h??1))*100):null;
 return <ScrollView contentInsetAdjustmentBehavior="automatic" refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh}/>} contentContainerStyle={{padding:16,gap:18,paddingBottom:72}}>
  <OSHero eyebrow="KLEENESTOS · PROGRESSION" title="Economy & Progression Studio" body="Operate XP policy, platform objectives and the fresh-content supply engine from one audited control plane. Quests, missions, challenges, journeys, campaigns and contests all stay on the canonical progression event stream."/>
  {error?<Text style={{color:osColors.danger,fontWeight:'800'}}>{error}</Text>:null}{message?<Text style={{color:osColors.good,fontWeight:'800'}}>{message}</Text>:null}
  <View style={{flexDirection:'row',flexWrap:'wrap',gap:10}}><HealthCard label="XP issuance" value={Number(data?.xpAwarded??0).toLocaleString()} detail={`${Number(data?.xpLast24h??0).toLocaleString()} in 24h${velocityDelta==null?'':` · ${velocityDelta>=0?'+':''}${velocityDelta}%`}`}/><HealthCard label="Participants" value={Number(data?.usersWithXp??0).toLocaleString()} detail="Users with awarded v2 XP"/><HealthCard label="Discoveries" value={Number(data?.discoveries??0).toLocaleString()} detail={`${Number(data?.onSiteDiscoveries??0).toLocaleString()} on-site live`}/><HealthCard label="Objectives" value={Number(data?.activeObjectives??0).toLocaleString()} detail={`${objectives.length.toLocaleString()} total in studio`}/></View>

  <View style={{gap:10}}><SectionHeader title="Progression supply" body="The server runs a daily idempotent supply job. Approved templates mint fresh time-boxed objectives without app releases or duplicate cycles."/>
   <View style={{flexDirection:'row',flexWrap:'wrap',gap:10}}>{kinds.map(value=><HealthCard key={value} label={titleCase(value)} value={Number(supply?.active_by_kind?.[value]??0).toLocaleString()} detail={`${Number(supply?.scheduled_by_kind?.[value]??0)} scheduled`}/>)}</View>
   <EntityRow title="Supply templates" subtitle={`${Number(supply?.templates.length??0)} approved generators`} meta={`${Number(supply?.expiring_72h.length??0)} expiring within 72h`}><StatusPill label="AUTOMATED" tone="good"/></EntityRow>
   {supply?.last_run?<EntityRow title="Last supply run" subtitle={`${Number(supply.last_run.created_count??0)} created · ${Number(supply.last_run.expired_count??0)} expired`} meta={supply.last_run.ran_at?new Date(String(supply.last_run.ran_at)).toLocaleString():''}/>:null}
   <PrimaryAction label={saving?'Refreshing…':'Refresh progression supply now'} onPress={runSupply} disabled={saving}/>
  </View>

  <View style={{gap:10}}><SectionHeader title="Progression Studio" body="Create and operate platform-wide objectives. Existing participant history is protected: archive used objectives instead of deleting them."/><PrimaryAction label="Create objective" onPress={beginCreate} disabled={saving}/><View style={{flexDirection:'row',flexWrap:'wrap',gap:8}}>{kinds.map(value=><StatusPill key={value} label={`${titleCase(value)} ${objectiveSummary[value]??0}`} tone={Number(supply?.active_by_kind?.[value]??0)>0?'good':'warning'}/>)}</View>{objectives.map(item=><EntityRow key={item.id} title={item.title} subtitle={`${titleCase(item.kind)} · ${titleCase(item.status)} · ${ruleValue(item.rules,'target','1')} × ${titleCase(ruleValue(item.rules,'action','activity'))}`} meta={`${item.completed}/${item.participants} completed`} onPress={()=>beginEdit(item)}><StatusPill label={item.status.toUpperCase()} tone={item.status==='active'?'good':item.status==='paused'?'warning':item.status==='archived'||item.status==='ended'?'neutral':'neutral'}/></EntityRow>)}</View>

  {editingObjective!==undefined?<ActionSheetCard title={editingObjective?`Edit ${editingObjective.title}`:'Create platform objective'} body="Every save and lifecycle change is server-authorized and written to the Owner audit trail.">
    <Text style={label}>Kind</Text><View style={chips}>{kinds.map(value=><Chip key={value} label={titleCase(value)} active={kind===value} onPress={()=>setKind(value)}/>)}</View>
    <Text style={label}>Title</Text><TextInput value={objectiveTitle} onChangeText={setObjectiveTitle} placeholder="Objective title" style={input}/>
    <Text style={label}>Stable code</Text><TextInput value={objectiveCode} onChangeText={setObjectiveCode} autoCapitalize="none" placeholder="objective-code" style={input}/>
    <Text style={label}>Description</Text><TextInput value={objectiveDescription} onChangeText={setObjectiveDescription} placeholder="What the participant should accomplish" multiline style={[input,{minHeight:84,textAlignVertical:'top'}]}/>
    <Text style={label}>Lifecycle</Text><View style={chips}>{statuses.map(value=><Chip key={value} label={titleCase(value)} active={objectiveStatus===value} onPress={()=>setObjectiveStatus(value)}/>)}</View>
    <Text style={label}>Progress action</Text><TextInput value={objectiveAction} onChangeText={setObjectiveAction} autoCapitalize="none" placeholder="verify_location" style={input}/><View style={chips}>{commonActions.map(value=><Chip key={value} label={titleCase(value)} active={objectiveAction===value} onPress={()=>setObjectiveAction(value)}/>)}</View>
    <Text style={label}>Target count</Text><TextInput value={objectiveTarget} onChangeText={setObjectiveTarget} keyboardType="number-pad" style={input}/>
    <Text style={label}>Displayed completion XP</Text><TextInput value={objectiveXp} onChangeText={setObjectiveXp} keyboardType="number-pad" style={input}/>
    <Text style={label}>Audience</Text><TextInput value={objectiveAudience} onChangeText={setObjectiveAudience} autoCapitalize="none" placeholder="consumer" style={input}/>
    <Text style={label}>Starts at (ISO date/time, optional)</Text><TextInput value={startsAt} onChangeText={setStartsAt} autoCapitalize="none" placeholder="2026-09-05T12:00:00Z" style={input}/>
    <Text style={label}>Ends at (ISO date/time, optional)</Text><TextInput value={endsAt} onChangeText={setEndsAt} autoCapitalize="none" placeholder="2026-09-12T12:00:00Z" style={input}/>
    <Text style={label}>Audit reason</Text><TextInput value={reason} onChangeText={setReason} style={input}/>
    <View style={chips}><PrimaryAction label={saving?'Saving…':editingObjective?'Save objective':'Create objective'} onPress={saveObjective} disabled={saving||!objectiveTitle.trim()||!objectiveCode.trim()||!objectiveAction.trim()||!reason.trim()}/><PrimaryAction label="Cancel" onPress={()=>setEditingObjective(undefined)} disabled={saving}/></View>
    {editingObjective?<><Text style={label}>Lifecycle commands</Text><View style={chips}>{editingObjective.status!=='active'?<PrimaryAction label="Activate objective" onPress={()=>changeObjectiveStatus(editingObjective,'active')} disabled={saving}/>:<PrimaryAction label="Pause objective" onPress={()=>changeObjectiveStatus(editingObjective,'paused')} disabled={saving}/>}<PrimaryAction label="Archive objective" onPress={()=>changeObjectiveStatus(editingObjective,'archived')} disabled={saving}/><PrimaryAction label="Delete objective" onPress={()=>deleteObjective(editingObjective)} disabled={saving||editingObjective.participants>0}/></View>{editingObjective.participants>0?<Text style={{color:osColors.muted}}>Delete is disabled because this objective has participant history. Archive preserves auditability and historical progression.</Text>:null}</>:null}
  </ActionSheetCard>:null}

  <View style={{gap:9}}><SectionHeader title="Evidence tiers" body="Discovery confidence and XP strength are distinct, visible operating signals."/>{data?.evidenceTiers.map((item:any)=><EntityRow key={String(item.tier)} title={tierLabels[String(item.tier)]??`Tier ${item.tier}`} subtitle={`${Number(item.count??0).toLocaleString()} discoveries`}><StatusPill label={`TIER ${item.tier}`} tone={Number(item.tier)>=4?'good':'neutral'}/></EntityRow>)}</View>
  <View style={{gap:9}}><SectionHeader title="Level distribution" body="Actual user distribution derived from awarded XP and canonical global thresholds."/>{data?.levelDistribution.map((item:any)=><EntityRow key={String(item.level)} title={`Level ${item.level}`} subtitle={`${Number(item.users??0).toLocaleString()} users`}/>)}</View>
  <View style={{gap:9}}><SectionHeader title="Objective mix" body="Live mix from the canonical objective stream."/>{Object.entries(data?.objectiveKinds??{}).map(([value,count])=><EntityRow key={value} title={titleCase(value)} subtitle={`${Number(count).toLocaleString()} active`}/>)}</View>
  <View style={{gap:9}}><SectionHeader title="XP by action" body="Where the economy is issuing value right now."/>{data?.awardsByAction.slice(0,20).map((item:any)=><EntityRow key={String(item.action)} title={titleCase(String(item.action))} subtitle={`${Number(item.xp??0).toLocaleString()} XP`} meta={`${Number(item.events??0).toLocaleString()} awards`}/>)}</View>
  <View style={{gap:9}}><SectionHeader title="Suspicious velocity" body="Candidates are surfaced for review when 24-hour reward volume is unusually high."/>{data?.anomalyCandidates.length?data.anomalyCandidates.map((item:any)=><EntityRow key={String(item.user_id)} title={`User ${String(item.user_id).slice(0,8)}…`} subtitle={`${Number(item.xp_24h??0).toLocaleString()} XP in 24h`} meta={`${Number(item.events_24h??0).toLocaleString()} events`}><StatusPill label="REVIEW" tone="warning"/></EntityRow>):<EntityRow title="No current anomaly candidates" subtitle="No user crossed the configured high-velocity review threshold in the last 24 hours."><StatusPill label="HEALTHY" tone="good"/></EntityRow>}</View>
  <View style={{gap:9}}><SectionHeader title="XP policy controls" body="Select an action to change base XP, cooldown, daily cap or enablement. Every change is Owner-authorized and audited."/>{data?.xpActionCatalog.map((item:any)=><EntityRow key={String(item.action)} title={titleCase(String(item.action))} subtitle={`${Number(item.base_xp??0)} base XP · ${Number(item.cooldown_seconds??0)}s cooldown`} meta={`${item.max_per_day==null?'No daily cap':`${item.max_per_day}/day`} · ${item.enabled?'Enabled':'Disabled'}`} onPress={()=>chooseAction(item)}/>)}</View>
  {selectedAction?<ActionSheetCard title={`Tune ${titleCase(String(selectedAction.action))}`} body="This changes the live reward policy. Verification confidence remains separate from XP."><Text style={label}>Base XP</Text><TextInput keyboardType="number-pad" value={baseXp} onChangeText={setBaseXp} style={input}/><Text style={label}>Cooldown seconds</Text><TextInput keyboardType="number-pad" value={cooldown} onChangeText={setCooldown} style={input}/><Text style={label}>Max per day (blank = unlimited)</Text><TextInput keyboardType="number-pad" value={maxPerDay} onChangeText={setMaxPerDay} style={input}/><Pressable onPress={()=>setEnabled(v=>!v)}><StatusPill label={enabled?'ENABLED':'DISABLED'} tone={enabled?'good':'danger'}/></Pressable><Text style={label}>Audit reason</Text><TextInput value={reason} onChangeText={setReason} style={input}/><View style={chips}><PrimaryAction label={saving?'Saving…':'Apply XP policy'} onPress={saveAction} disabled={saving||!reason.trim()}/><PrimaryAction label="Cancel" onPress={()=>setSelectedAction(null)} disabled={saving}/></View></ActionSheetCard>:null}
  <View style={{gap:9}}><SectionHeader title="Recent high-value events"/>{data?.recentHighValueEvents.slice(0,15).map((item:any)=><EntityRow key={String(item.id)} title={titleCase(String(item.action))} subtitle={`${Number(item.xp_awarded??0).toLocaleString()} XP · evidence tier ${Number(item.evidence_tier??0)}`} meta={item.created_at?new Date(String(item.created_at)).toLocaleString():''}/>)}</View>
 </ScrollView>
}

function Chip({label:chipLabel,active,onPress}:{label:string;active:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={{borderRadius:999,paddingHorizontal:11,paddingVertical:8,backgroundColor:active?osColors.ink:'#edf3ef',borderWidth:1,borderColor:active?osColors.ink:osColors.border}}><Text style={{fontWeight:'900',fontSize:12,color:active?'white':osColors.ink}}>{chipLabel}</Text></Pressable>}
const label={fontWeight:'900',color:osColors.ink,fontSize:12} as const;
const input={backgroundColor:'white',borderRadius:12,paddingHorizontal:12,paddingVertical:11,borderWidth:1,borderColor:osColors.border,color:osColors.ink} as const;
const chips={flexDirection:'row',flexWrap:'wrap',gap:8} as const;
